--VERIFICAR DATOS DE CONEXION REAL Y DE PRUEBAS
--VERFICAR CLIENTE
--VALIDA INCAPACIDADES
DECLARE @Mes as Varchar (max)
Set @Mes='202403'
PRINT 'INCAPACIDADES'
	IF EXISTS (SELECT * FROM CONCEPTOS C LEFT JOIN MAPEO_NOM_ELEC M on(C.Cod_Concepto=M.Cod_Concepto and Cod_Tipo='1') WHERE C.Tipo_Concepto='I' and Cod_Alterno2 not in ('COMUN','PROFESIONAL','LABORAL'))  BEGIN SELECT 'REVISAR COD_ALTERNO2',* FROM CONCEPTOS C LEFT JOIN MAPEO_NOM_ELEC M on(C.Cod_Concepto=M.Cod_Concepto and Cod_Tipo='1')WHERE C.Tipo_Concepto='I' and Cod_Alterno2 not in ('COMUN','PROFESIONAL','LABORAL')  END 
PRINT 'VALIDA TIPOS DE CONTRATO'
	Select 'REVISAR_TIPOS_DE_CONTRATO',* from EMPLEADOS WHERE Tipo_Contrato not in (SELECT Cod_Concepto FROM MAPEO_NOM_ELEC WHERE Cod_Tipo = '5') and Estado<>'R'
PRINT 'VALIDA TIPOS DE DOCUMENTO'
	Select 'REVISAR_TIPOS_DE_DOCUMENTO',* from EMPLEADOS WHERE Tip_Documento not in (SELECT Cod_Concepto FROM MAPEO_NOM_ELEC WHERE Cod_Tipo = '3') and Estado<>'R'
PRINT 'VALIDA CORREOS'
	Select 'REVISAR_CORREOS',* from EMPLEADOS WHERE (Dir_Elec not like '%@%' or Dir_Elec not like '%.%' or Dir_Elec like '%,%' or lower(Dir_Elec) like '%systemsltda.com%' or (lower(Dir_Elec) not like '%.co%' and lower(Dir_Elec) not like '%.es%' and lower(Dir_Elec) not like '%.net%')) and Estado<>'R' 
PRINT 'VALIDA DIRECCION'
	Select 'REVISAR_DIRECCION',* from EMPLEADOS WHERE Direccion ='' and Estado<>'R'
PRINT 'VALIDA COD_CIUDAD'
	Select 'REVISAR_COD_CIUDAD',Cod_Ciudad,* from EMPLEADOS WHERE (Cod_Ciudad ='' or Cod_Ciudad ='0') and Estado<>'R'
PRINT 'VALIDA CONCEPTOS EXISTAN EN MAPEO'
		select distinct 'CONCEPTO_NO_EXISTE_EN_MAPEO',Cod_Concepto,Fec_Nomina from HISTORICO where  Estado='P' and SUBSTRING(Fec_Nomina,1,6)=@Mes AND Cod_Concepto not in (Select Cod_Concepto from MAPEO_NOM_ELEC where  Cod_Tipo='1')
PRINT 'VALIDA SOLIDARIDAD PENSIONAL'
	select 'REVISAR_%_SOLIDARIDAD_PENSIONAL',* from HISTORICO WHERE Estado='P' and SUBSTRING(Fec_Nomina,1,6)=@Mes and Cod_Concepto='11' and Porcentaje='0'
PRINT 'VALIDA DIAS PRESTACIONES'
	select 'REVISAR_DIAS_NOVEDAD_PRESTACIONES',* from HISTORICO WHERE Estado='P'  and SUBSTRING(Fec_Nomina,1,6)=@Mes and Cod_Concepto IN ('97','21','98','20','19') and Dias_Novedad<='0'
PRINT 'VALIDA CONCEPTOS REPETIDOS'
	SELECT 'REVISAR CONCEPTOS REPETIDOS',Cod_Concepto,COUNT(Nom_Concepto) [Registros_Repetidos] FROM CONCEPTOS group by Cod_Concepto HAVING COUNT(Nom_Concepto)>1
PRINT 'VALIDA CONCEPTOS REPETIDOS EN MAPEO'
	SELECT 'REVISAR CONCEPTOS REPETIDOS MAPEO_NOM_ELEC',Cod_Concepto,Cod_Alterno,COUNT(Cod_Concepto) [Registros_Repetidos] FROM MAPEO_NOM_ELEC WHERE Dian_xml<>'NIE000' group by Cod_Concepto,Cod_Alterno HAVING COUNT(Cod_Concepto)>1
PRINT 'VALIDA MAPEO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE056 ' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE071' and Cod_Alterno<>'AUXILIO_DE_TRANSPORTE'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE078' and Cod_Alterno<>'HORA_EXTRA_DIURNA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE177' and Cod_Alterno<>'RETENCION_FUENTE'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE163' and Cod_Alterno<>'SALUD'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE166' and Cod_Alterno<>'FONDO_PENSION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE093' and Cod_Alterno<>'HORA_EXTRA_DIURNA_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE112' and Cod_Alterno<>'VACACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE116' and Cod_Alterno<>'VACACION_COMPENSADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE168' and Cod_Alterno<>'FONDO_SOLIDARIDAD_PENSIONAL'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE139' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE155' and Cod_Alterno<>'COMISION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE181' and Cod_Alterno<>'EMBARGO_FISCAL'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE194' and Cod_Alterno<>'ANTICIPO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE195' and Cod_Alterno<>'PAGO_TERCERO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE196' and Cod_Alterno<>'ANTICIPO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE118' and Cod_Alterno<>'PRIMA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE120' and Cod_Alterno<>'CESANTIAS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE122' and Cod_Alterno<>'CESANTIAS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE131' and Cod_Alterno<>'LICENCIA_PATERNIDAD'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE120' and Cod_Alterno<>'CESANTIAS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE135' and Cod_Alterno<>'LICENCIA_REMUNERADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE138' and Cod_Alterno<>'LICENCIA_NO_REMUNERADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE127' and Cod_Alterno<>'INCAPACIDAD '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE172' and Cod_Alterno<>'SINDICATO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE138' and Cod_Alterno<>'LICENCIA_NO_REMUNERADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE138' and Cod_Alterno<>'LICENCIA_NO_REMUNERADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE160' and Cod_Alterno<>'INDEMNIZACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE072' and Cod_Alterno<>'VIATICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE127' and Cod_Alterno<>'INCAPACIDAD '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE194' and Cod_Alterno<>'ANTICIPO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE088' and Cod_Alterno<>'HORA_RECARGO_NOCTURNO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE083' and Cod_Alterno<>'HORA_EXTRA_NOCTURNA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE118' and Cod_Alterno<>'PRIMA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE103' and Cod_Alterno<>'HORA_EXTRA_NOCTURNA_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE118' and Cod_Alterno<>'PRIMA '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE131' and Cod_Alterno<>'LICENCIA_PATERNIDAD'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE093' and Cod_Alterno<>'HORA_EXTRA_DIURNA_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE156' and Cod_Alterno<>'DOTACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE112' and Cod_Alterno<>'VACACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE098' and Cod_Alterno<>'HORA_RECARGO_DIURNA_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE108' and Cod_Alterno<>'HORA_RECARGO_NOCTURNO_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE108' and Cod_Alterno<>'HORA_RECARGO_NOCTURNO_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE093' and Cod_Alterno<>'HORA_EXTRA_DIURNA_DF'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE112' and Cod_Alterno<>'VACACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE140' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE157' and Cod_Alterno<>'APOYO_PRACTICA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE122' and Cod_Alterno<>'CESANTIAS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE122' and Cod_Alterno<>'CESANTIAS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE112' and Cod_Alterno<>'VACACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE152' and Cod_Alterno<>'BONO_EPCTV'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE176' and Cod_Alterno<>'LIBRANZA '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE159' and Cod_Alterno<>'BONIFICACION_RETIRO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE140' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE185' and Cod_Alterno<>'DEUDA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE176' and Cod_Alterno<>'LIBRANZA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE176' and Cod_Alterno<>'LIBRANZA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE135' and Cod_Alterno<>'LICENCIA_REMUNERADA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE180' and Cod_Alterno<>'COOPERATIVA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE160' and Cod_Alterno<>'INDEMNIZACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE154' and Cod_Alterno<>'BONO_EPCTV_ALIMENTACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE152' and Cod_Alterno<>'BONO_EPCTV'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE182' and Cod_Alterno<>'PLANES_COMPLEMENTARIOS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE159' and Cod_Alterno<>'BONIFICACION_RETIRO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE182' and Cod_Alterno<>'PLANES_COMPLEMENTARIOS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE140' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE140' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE182' and Cod_Alterno<>'PLANES_COMPLEMENTARIOS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE140' and Cod_Alterno<>'BONIFICACION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE180' and Cod_Alterno<>'COOPERATIVA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE127' and Cod_Alterno<>'INCAPACIDAD '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE201' and Cod_Alterno<>'REINTEGRO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE182' and Cod_Alterno<>'PLANES_COMPLEMENTARIOS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE176' and Cod_Alterno<>'LIBRANZA '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE148' and Cod_Alterno<>'OTRO_CONCEPTO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE155' and Cod_Alterno<>'COMISION'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE157' and Cod_Alterno<>'APOYO_PRACTICA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE073' and Cod_Alterno<>'VIATICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE182' and Cod_Alterno<>'PLANES_COMPLEMENTARIOS'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE196' and Cod_Alterno<>'ANTICIPO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE148' and Cod_Alterno<>'OTRO_CONCEPTO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE119' and Cod_Alterno<>'PRIMA '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE198' and Cod_Alterno<>'PENSION_VOLUNTARIA'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE148' and Cod_Alterno<>'OTRO_CONCEPTO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE201' and Cod_Alterno<>'REINTEGRO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE197' and Cod_Alterno<>'OTRA_DEDUCCION '
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE179' and Cod_Alterno<>'AFC'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE184' and Cod_Alterno<>'REINTEGRO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE071' and Cod_Alterno<>'AUXILIO_DE_TRANSPORTE'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE142' and Cod_Alterno<>'AUXILIO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE070' and Cod_Alterno<>'BASICO'
select * from MAPEO_NOM_ELEC where Dian_xml='NIE183' and Cod_Alterno<>'EDUCACION'