--****** SCRIPT SOLUCIONES *********--
-- 1. CONSULTAS
USE NOBOSZ

GO

-- 2. SOLUCIONES FIJAS DE ADECUACION EN BASE DE DATOS
USE NOBOSZ -- Estado: LOCAL | Descripción:
GO

-- 3. SOLUCIONES A NOVEDADES MENSUALES

USE NOBOSZ -- Estado: LOCAL | 2024_MARZO
INSERT INTO MAPEO_NOM_ELEC VALUES ('233',1,'NIE139','BONIFICACION',' ','BONO RECRUITING REWARDS','2021-12-30','A','1')
GO
-- prueba1
