--****** SCRIPT SOLUCIONES *********--
-- 1. CONSULTAS
USE NOLEOBURNETT
SELECT * FROM EMPLEADOS WHERE Cod_Empleado=5588
GO

-- 2. SOLUCIONES FIJAS DE ADECUACION EN BASE DE DATOS
USE NOLEOBURNETT -- Estado: LOCAL | Descripción:
GO

-- 3. SOLUCIONES A NOVEDADES MENSUALES

USE NOLEOBURNETT -- Estado: LOCAL | 2024_MARZO
UPDATE EMPLEADOS SET Dir_Elec='sebastian.lopezurrego@publiciscolombia.com' where Cod_Empleado=5588
GO