--****** SCRIPT SOLUCIONES *********--
-- 1. CONSULTAS
USE NOSAPIENT

GO

-- 2. SOLUCIONES FIJAS DE ADECUACION EN BASE DE DATOS
USE NOSAPIENT -- Estado: LOCAL | Descripción:
GO

-- 3. SOLUCIONES A NOVEDADES MENSUALES

USE NOSAPIENT -- Estado: LOCAL | 2024_MARZO
INSERT INTO MAPEO_NOM_ELEC VALUES ('233',1,'NIE139','BONIFICACION',' ','BONO RECRUITING REWARDS','2021-12-30','A','1')
GO